apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "gpt-lingualink-rest"
  name: "gpt-lingualink-rest"
  namespace: default
spec:
  capacity:
      storage: 500Gi
  volumeMode: Filesystem
  accessModes:
      - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data  # 外部磁盘的挂载路径
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "gpt-lingualink-rest"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        p1.cn/metric_path: /metrics
        p1.cn/scrape_port: "8000"
        p1.cn/should_be_scraped: "true"
        proxy.istio.io/config: |
          terminationDrainDuration: 20s
          holdApplicationUntilProxyStarts: true
      labels:
        app: open-webui
        org: gpt
        resource: container
    spec:
      serviceAccount: kyc
      containers:
        - env:
            - name: APP_ENV
              value: prod
            - name: VAULT_LOGIN_PATH
              valueFrom:
                configMapKeyRef:
                  key: vault_login_path
                  name: vault-config
          image: {{image-url}}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /debug/health
              port: 8000
              scheme: HTTP
            timeoutSeconds: 5
          name: "open-webui"
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /debug/health
              port: 8000
              scheme: HTTP
            timeoutSeconds: 10
          resources:
            limits:
              cpu: "8"
              memory: 16Gi
            requests:
              cpu: "1m"
              memory: 1Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      securityContext: { }
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 15
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 15